# Generated by Django 4.1.3 on 2022-11-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_flat', models.CharField(max_length=50, unique=True, verbose_name='Название квартиры')),
                ('cod_platelshika', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код плательщика')),
                ('period_oplaty', models.CharField(max_length=50, verbose_name='Период оплаты')),
                ('summa', models.CharField(max_length=50, verbose_name='Сумма счета')),
            ],
        ),
    ]
