# Generated by Django 4.1.3 on 2023-01-10 11:31

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_flat', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название квартиры')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsEpd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_flat', models.CharField(max_length=60, verbose_name='Название квартиры')),
                ('date_pars', models.DateTimeField(auto_now=True, null=True)),
                ('cod_platelshika', models.CharField(db_index=True, max_length=50, verbose_name='Код плательщика')),
                ('period_oplaty', models.CharField(max_length=50, verbose_name='Период оплаты')),
                ('summa', models.CharField(max_length=50, verbose_name='Сумма счета')),
                ('bill_save_pdf', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/Bill_pdf/10-01-2023/', location='Bill_pdf/10-01-2023/'), upload_to='10-01-2023/', verbose_name='Счет')),
                ('flats', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mos_sel.flat')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['name_flat'],
            },
        ),
    ]
