# Generated by Django 4.1.3 on 2022-11-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mos_sel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='cod_platelshika',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Код плательщика'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='name_flat',
            field=models.CharField(max_length=50, verbose_name='Название квартиры'),
        ),
    ]
