# Generated by Django 4.1.3 on 2023-01-10 14:31

import django.core.files.storage
from django.db import migrations, models
import mos_sel.models


class Migration(migrations.Migration):

    dependencies = [
        ('mos_sel', '0004_alter_paymentsepd_bill_save_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsepd',
            name='bill_save_pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=mos_sel.models.PaymentsEpd.get_path), upload_to=mos_sel.models.PaymentsEpd.get_path, verbose_name='Счет'),
        ),
    ]
