# Generated by Django 4.1.3 on 2023-01-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mos_sel', '0010_alter_paymentsepd_bill_save_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsepd',
            name='period_oplaty',
            field=models.DateField(verbose_name='Период оплаты'),
        ),
    ]
