# Generated by Django 4.1.3 on 2023-01-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mos_sel', '0011_alter_paymentsepd_period_oplaty'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsepd',
            name='amount_of_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплачено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsepd',
            name='date_of_payment',
            field=models.DateField(null=True, verbose_name='Дата оплаты счета'),
        ),
    ]
