# Generated by Django 4.1.3 on 2023-01-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mos_sel', '0013_alter_paymentsepd_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsepd',
            name='date_of_payment',
            field=models.DateField(null=True, verbose_name='Дата оплаты счета'),
        ),
    ]
